# 测试环境配置
spring:
  datasource:
    url: jdbc:mysql://test-mysql:3306/live_finance_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  
  redis:
    host: test-redis
    port: 6379
    database: 2

  cloud:
    consul:
      host: test-consul
      port: 8500

# 日志级别
logging:
  level:
    root: INFO
    com.liveroom.finance: INFO
