# 测试环境配置 - Docker容器化

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db1?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  
  redis:
    host: shared-redis
    port: 6379
    database: 1

logging:
  level:
    root: INFO
    com.liveroom: INFO

consul:
  host: consul
  port: 8500
