# 开发环境配置 - 本地开发

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/live_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

# 服务URL配置 - 本地开发
service:
  anchor:
    url: http://localhost:8081
  audience:
    url: http://localhost:8082
  finance:
    url: http://localhost:8083
  redis:
    url: http://localhost:8085

logging:
  level:
    root: INFO
    com.liveroom: DEBUG
